#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

make -s bin/golangci-lint >/dev/null
bin/golangci-lint fmt

cd benchmarks
../bin/golangci-lint fmt --config ../.golangci.yaml .
