#!/bin/bash

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"
make -s bin/go-fuzz bin/go-fuzz-build bin/jq
PATH="$(pwd)/bin:$PATH"

GOBIN="$(pwd)/bin" GO111MODULE=off go get golang.org/dl/gotip

if ! gotip version; then
  gotip download dev.fuzz
fi

gotip test -run '^$' -fuzz FuzzMe -v "$@" .
