#!/bin/bash

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

timeout="$1"

if [ -z "$timeout" ]; then
  echo 'usage: script/fuzz-timeout <timeout in seconds>'
  exit 2
fi

PATH="$(go env GOROOT)/bin:$(pwd)/bin:$PATH"

mkdir -p tmp

GO_FUZZ_VERSION="$(cat script/.go-fuzz-version)"

go get "github.com/dvyukov/go-fuzz@$GO_FUZZ_VERSION"
trap "go mod tidy" EXIT

script/go-fuzz-build -o tmp/fuzz-rjson.zip

script/go-fuzz -dup -bin tmp/fuzz-rjson.zip -workdir testdata/fuzz &

pid=$!

sleep "$timeout"

kill -2 $pid

echo "done"
