#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

make -s bin/golangci-lint bin/shellcheck
bin/golangci-lint run --build-tags gofuzz
bin/shellcheck script/*

cd benchmarks
../bin/golangci-lint run --config ../.golangci.yaml
