name: ci
on: [ push, workflow_dispatch ]
jobs:
  cibuild:
    name: cibuild
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: WillAbides/setup-go-faster@v1
        id: setup-go
        with:
          go-version: '1.15.x'
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-go.outputs.GOCACHE }}
            ${{ steps.setup-go.outputs.GOMODCACHE }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - run: script/generate --check
      - run: script/test
      - run: script/lint
